### ISSUE TITLE
Should scrollSource == null cause a fall back to the document scrollingElement, rather than document element?

### ISSUE THREAD

**Issue by stephenmcgruer** [WICG/scroll-animations#14]
Currently the spec for scrollSource says (https://wicg.github.io/scroll-animations/#dom-scrolltimeline-scrollsource):

"If this is not specified, the document element of the active document for the current browsing context, as determined at the time the ScrollTimeline is constructed, is used."

It seems to me like this should probably fall back to document.scrollingElement (https://drafts.csswg.org/cssom-view/#dom-document-scrollingelement) instead?

**Comment by theres-waldo** [comment]
You're right, we should be using document.scrollingElement. I didn't know about document.scrollingElement at the time I wrote this spec.
