### ISSUE TITLE
When should orientation = 'auto' be resolved?

### ISSUE THREAD

**Issue by stephenmcgruer** [WICG/scroll-animations#15]
This question came up during the Chromium implementation of ScrollTimeline. The definition of orientation states:

"auto
If only one direction is scrollable, selects that direction. Otherwise selects the direction along the block axis."

However it isn't explicit about *when* this direction should be selected. If a ScrollTimeline is constructed as follows:

`var timeline = new ScrollTrigger({ scrollSource: scroller, orientation: "auto" }) `

When should the orientation = 'auto' be resolved - at construction time, or every time currentTime is called? (Possibly changing from block to inline in the latter case, e.g. if the scroller content changes).

**Comment by theres-waldo** [comment]
The intention is to resolve it at construction time (similar to when the scrollSource isn't specified). You're right that this should be said explicitly in the spec.

**Comment by stephenmcgruer** [comment]
Closing this since 'auto' has been removed from the spec. Issue #16 will remain open for now to track any re-implementation of 'auto'.
