### ISSUE TITLE
Start == End scroll offsets can lead to division by zero

### ISSUE THREAD

**Issue by majido** [WICG/scroll-animations#21]
It is possible to have start and end offset that are equal. This can lead to a division by zero when [calculating currentTime](https://wicg.github.io/scroll-animations/#current-time-algorithm). The spec should explicitly call this out and return early before trying to compute current time. I think a sensible option is to return undefined in this case.

> (current scroll offset - startScrollOffset) / (endScrollOffset - startScrollOffset) × effective time range

**Comment by birtles** [comment]
How can this happen? If `startScrollOffset == endScrollOffset` then _current scroll offset_ must be either < `startScrollOffset` or >= `endScrollOffset` so we should have hit an early return in step 3 or 4, right?

**Comment by stephenmcgruer** [comment]
That is an excellent point (and I am somewhat embarrassed to have missed it -_-).

We should check we are ok with the behavior of fill modes in that instance then. Currently when `startScrollOffset == endScrollOffset`:

**fill is 'none'**: current time is always unresolved
**fill is 'forwards'**: current time is unresolved until `current scroll offset == startScrollOffset == endScrollOffset`, then it is the `effective time range` from then on.
**fill is 'backwards'**: current time is 0 until `current scroll offset == startScrollOffset == endScrollOffset`, then it is unresolved from then on.
**fill is 'both'**: current time is 0 until `current scroll offset == startScrollOffset == endScrollOffset`, then it is the `effective time range` from then on.

This seems ok to me (the timeline essentially has no 'active' time, it just flips from not-started to already-finished when current scroll offset advances to the flip point), so unless @majido has other thoughts I think we should close this and abandon my PR.

**Comment by birtles** [comment]
That behavior matches what we do for timed things so I think it's what we want to try initially unless we find that it just doesn't make sense in the context of scroll.
