### ISSUE TITLE
horizontal/vertical should specify whether they follow the direction/writing-mode

### ISSUE THREAD

**Issue by stephenmcgruer** [WICG/scroll-animations#22]
Currently vertical and horizontal are specified as:

```
horizontal
    Selects the horizontal direction.
vertical
    Selects the vertical direction
```
When `writing-mode` and `direction` are specified however, this can cause the beginning edges of an overflow region to be at the right/bottom.

It is not clear from the spec whether in these cases the orientation vector should also start from the right/bottom, or should stick with the physical top/left. The naive thinking is yes it should, but that only works if one is animating logical properties - consider what might happen if you animate `transform: translateX(...)`. (The logical/physical issue is sort of a larger meta issue which I will file another issue about. This particular issue is about the fact that the spec doesn't make it clear what the horizontal/vertical directions are in the face of rtl.)

For an example, see https://output.jsbin.com/ruterik . This can be run in Chrome M71 (currently Canary) with the Experimental Web Platform Features flag on. It will show that we currently do follow the writing direction for `horizontal`/`vertical`, but it's not clear whether this is correct by the spec.

**Comment by stephenmcgruer** [comment]
Example in a gist in-case anything happens to jsbin: https://gist.github.com/stephenmcgruer/85e6a9c9506e70451e36cbcc0d932666

**Comment by stephenmcgruer** [comment]
Having discussed this since, our current suggestion is that horizontal/vertical should use the physical vectors, and not change for writing mode. This allows for developers to animate both logical properties (e.g. `margin-inline-start`) using block/inline ScrollTimelines, and physical properties (e.g. `transform`) using horizontal/vertical ScrollTimelines with the least amount of unexpected behavior (we think).

I plan to send out a PR making this explicit.

**Comment by majido** [comment]
I agree about the above suggestion.

I think there is a few additional pieces that the spec needs to clarify more to make this work:
- **current scroll offset**: I believe the scroll offset should match the vector accordingly. e.g., for a horizontal ltr scroller of size 100px the scroll starts from top right corner. 
Here we can say the *physical* horizontal scroll offset is `100px`  this matches Element.scrollLeft but the *logical* inline scroll offset is `0`. This means that creating a ScrollTimeline with direction: `horizontal` will produce currentTime=Max but with direction `inline` should give currentTime=0.
- **logic for fill modes**: current wording for fill mode behavior relies on offset being larger that end or start. I think we have to clarify that "larger" should be interpreted logically or physically depending on the direction.

**Comment by stephenmcgruer** [comment]
**current scroll offset**: Currently the language is:

> Otherwise, let current scroll offset be the current scroll offset of scrollSource in the direction specified by orientation.

To me, that says it is matching the orientation vector. Do you feel there is a specific improvement we could make here? Obviously it is an issue that 'scroll offset' isn't defined in any spec afaik.

**logic for fill modes**: Assuming that scroll offsets (and startScrollOffset/etc) are properly directional for the orientation, then I don't think anything needs to change here. Can you explain where you think the problem is?

**Comment by majido** [comment]
The current wording for orientation sounds reasonable. And given that the spec requires all the offsets ( *current*, *start* and *end* scroll offsets) to be resolved considering the orientation then it seems that  a correct implementation should take into account the same orientation vector when doing comparison or computing delta.

To make it concrete here is an example:

```html
<div id="source" style="direction:rtl; overflow:scroll; width:100px;"> 
   <!-- cause the parent to  overflow horizontally for 100px -->
   <div style="width:200px"></div>
</div>

<script>
const logicalTimeline = new ScrollTimeline({scrollSource: source, orientation: 'inline', timeRange: 1}
const physicalTimeline = new ScrollTimeline({scrollSource: source, orientation: 'horizontal', timeRange: 1}

// scroll logically 40%  
source.scrollLeft = -40;  

console.log(`logical ${logicalTimeline.currentTime}`);
console.log(`physical ${physicalTimeline.currentTime}`);

</script>
```

I expect this to output:

```
logical 0.4
physical 0.6
```

In case of logical orientation, scroll timeline start is right side and end is left side. So by scrolling from right to left, the time goes from 0 to 1 and current time is at 0.4.

In case of physical orientation, scroll timeline start is left side and end is right side. So by scrolling from right to left, the time goes from 1 to 0 and current time is at 0.6.

I think this is a reasonable behavior.

Note that this is different from how scrollLeft is supposed to behave which goes from 0 to negative value in RTL case. Though this is not consistently implemented in practice.

**Comment by majido** [comment]
I wonder if it makes sense to have one of the examples (existing or a new one) in the spec  use logical directions to make this more.

**Comment by stephenmcgruer** [comment]
Ack. I think this issue can be closed now.
