### ISSUE TITLE
Wrap examples in `prefers-reduced-motion`

### ISSUE THREAD

**Issue by jensimmons** [WICG/scroll-animations#42]
I posted a question about this spec to Twitter, and @rogerjohansson [replied with](https://twitter.com/rogerjohansson/status/1108982231631044608) a good suggestion. 

> All examples should wrap the code in `prefers-reduced-motion: no-preference`.

I think that's a terrific idea. I know it'd add extra lines of code to the spec, while adding no value to the spec writers or implementors, but it would go a long way in emphasizing to the web industry that they shouldn't deliver scroll-driven animations to people who don't want them / can't handle them — and that doing so is very simple.

**Comment by stephenmcgruer** [comment]
Happening to be the person who also implemented [prefers-reduced-motion in Chrome](https://docs.google.com/document/d/1aZnSfg7I-xbRBYui5jkUIdbIgZ5jK9u-CUplPFU_tC8/view), I agree! Will put together a change for this later today.
