### ISSUE TITLE
Specify which document element is used if no scrollSource is specified

### ISSUE THREAD

**Issue by theres-waldo** [WICG/scroll-animations#5]
The spec says that if a `ScrollTimeline`'s `scrollSource` is not specified, "the document element is used".

We need to specify _which_ document's document element is used, and when that determination is made (e.g. getter call time, constructor time, ...).

**Comment by theres-waldo** [comment]
Suggested resolution: the document element of the `scrollSource`'s _owner document_ is used, and this determination is made at `ScrollTimeline` construction time.

**Comment by theres-waldo** [comment]
Sorry, that proposed resolution doesn't make sense, since the premise is that `scrollSource` is not specified. The answer should instead be something like "the document loaded in the current window".

**Comment by theres-waldo** [comment]
Suggested resolution: the document element of the document loaded in the current window is used.

**Comment by birtles** [comment]
Elsewhere we refer to the [active document](https://html.spec.whatwg.org/multipage/browsers.html#active-document) for the [current browsing context](https://html.spec.whatwg.org/multipage/browsers.html#browsing-context).

**Comment by theres-waldo** [comment]
Updates spec to say we use the document element of the active document for the current browsing context, as suggested, and that this determination is made at the time the `ScrollTimeline` is constructed.

**Comment by bzbarsky** [comment]
Filed https://github.com/WICG/scroll-animations/issues/11 on the fallout from this change.
