### ISSUE TITLE
update JavaScript example

### ISSUE THREAD

**Issue by zouhir** [WICG/scroll-animations#55]
The following JS example https://wicg.github.io/scroll-animations/#timeline-examples uses `trigger` options property and `ScrollTrigger` interface which are not documented anywhere and my understanding is they won't be implemented.

it'd be good to outline another solution using the most current & polyfilled API syntax.

**Comment by majido** [comment]
Hey this repository is outdated. I thought we have already archived it but apparently not.

Would you mind filing this issue under here: https://github.com/w3c/csswg-drafts/issues
The specification name there is scroll-animations-1.
