### ISSUE TITLE
Fix GitHub issues link to point to this WICG repo

### ISSUE THREAD

**Issue by RByers** [WICG/scroll-animations#8]
I used the GitHub issues link at the top of the spec to file [an issue](https://github.com/w3c/csswg-drafts/issues/819), but csswg-drafts is probably not the right repro for these issues ;-)

**Comment by theres-waldo** [comment]
Hmm. The issues link is not specified in the Bikeshed source - it appears to be generated by Bikeshed on the basis that the specified "Group" is CSSWG.

Web Animations has a similar issue (for which I just filed https://github.com/w3c/web-animations/issues/177) - there, the "Group" is "fxtf", and the issues link is accordingly https://github.com/w3c/fxtf-drafts/labels/web-animations-1, but the issue tracker actually used for Web Animations is https://github.com/w3c/web-animations/issues.

**Comment by theres-waldo** [comment]
Ok, I figured out how to get Bikeshed to override the default link. Fixed now.
