### ISSUE TITLE
Mention design constraint of not blocking scrolling?

### ISSUE THREAD

**Issue by RByers** [WICG/scroll-animations#9]
Depending on exactly how your interpret it, the [avoiding cycles](https://wicg.github.io/scroll-animations/#avoiding-cycles) section implies that scrolling may need to block on JavaScript / layout.

For blink (and probably also at least Edge) that is a non-starter.  Ensuring scrolling never blocks on the main thread has been our #1 scroll performance effort for several years, we're unwilling to allow that without an explicit scary-sounding opt-in API and a mitigation strategy (eg. "intervention" that applies on  sites whose performance isn't good enough to permit a reasonable user experience on low end phones).

Is there agreement on this non-blocking design constraint for scroll animations?  If so, perhaps it's worth mentioning in the introduction somewhere?

/cc @majido @flackr @shans

**Comment by theres-waldo** [comment]
The intent is most certainly not to block scrolling on JavaScript or layout!

In fact, one of the main motivations for this proposal is to allow web authors to express scroll-linked effects - such as parallax - in such a way that the effect can be updated in sync with scrolling without blocking on JavaScript.

I will clarify the "avoiding cycles" section to make this clear.

**Comment by theres-waldo** [comment]
I added mention of asynchronous scrolling to both the Introduction and the Avoiding Cycles section. Please let me know if this addresses your concerns. Thanks!

**Comment by theres-waldo** [comment]
I'm going to assume that the clarifications address this concern to your satisfaction, and close this issue. If they don't please feel free to reopen and say more.

**Comment by theres-waldo** [comment]
(The clarifications were added in https://github.com/WICG/scroll-animations/commit/e71ca23cd6c856a280168006216421a615738e00).

**Comment by RByers** [comment]
Shoot, sorry I missed your ping.  Yes those clarifications are awesome - thank you!
